export interface Item {
  id: number;
  name: string;
  category: string;
}

// 150個のアイテムデータ
export const ITEMS: Item[] = [
  // 狐関連 (20個)
  { id: 1, name: '白狐', category: 'fox' },
  { id: 2, name: '赤狐', category: 'fox' },
  { id: 3, name: '銀狐', category: 'fox' },
  { id: 4, name: '九尾の狐', category: 'fox' },
  { id: 5, name: '子狐', category: 'fox' },
  { id: 6, name: '狐の面', category: 'fox-item' },
  { id: 7, name: '狐火', category: 'fox-item' },
  { id: 8, name: '狐の尻尾', category: 'fox-item' },
  { id: 9, name: '狐のベル', category: 'fox-item' },
  { id: 10, name: '狐の玉', category: 'fox-item' },
  { id: 11, name: '狐柄の巾着', category: 'fox-item' },
  { id: 12, name: '狐耳', category: 'fox-item' },
  { id: 13, name: '稲荷寿司', category: 'fox-item' },
  { id: 14, name: '鳥居', category: 'fox-item' },
  { id: 15, name: '狐提灯', category: 'fox-item' },
  { id: 16, name: '神社のお守り', category: 'fox-item' },
  { id: 17, name: '絵馬', category: 'fox-item' },
  { id: 18, name: '狐の足跡', category: 'fox-item' },
  { id: 19, name: '狐笛', category: 'fox-item' },
  { id: 20, name: '狐の巻物', category: 'fox-item' },
  
  // 魚 (15個)
  { id: 21, name: '金魚', category: 'fish' },
  { id: 22, name: '鯛', category: 'fish' },
  { id: 23, name: '鮭', category: 'fish' },
  { id: 24, name: 'マグロ', category: 'fish' },
  { id: 25, name: 'イカ', category: 'fish' },
  { id: 26, name: 'タコ', category: 'fish' },
  { id: 27, name: 'エビ', category: 'fish' },
  { id: 28, name: 'カニ', category: 'fish' },
  { id: 29, name: 'ヒトデ', category: 'fish' },
  { id: 30, name: '貝殻', category: 'fish' },
  { id: 31, name: 'クラゲ', category: 'fish' },
  { id: 32, name: 'フグ', category: 'fish' },
  { id: 33, name: 'アンコウ', category: 'fish' },
  { id: 34, name: 'ウナギ', category: 'fish' },
  { id: 35, name: 'クジラ', category: 'fish' },
  
  // 食べ物 (20個)
  { id: 36, name: 'おにぎり', category: 'food' },
  { id: 37, name: '団子', category: 'food' },
  { id: 38, name: 'お餅', category: 'food' },
  { id: 39, name: 'どら焼き', category: 'food' },
  { id: 40, name: '饅頭', category: 'food' },
  { id: 41, name: 'ラーメン', category: 'food' },
  { id: 42, name: 'カレー', category: 'food' },
  { id: 43, name: 'お寿司', category: 'food' },
  { id: 44, name: '天ぷら', category: 'food' },
  { id: 45, name: 'おでん', category: 'food' },
  { id: 46, name: 'たい焼き', category: 'food' },
  { id: 47, name: 'お好み焼き', category: 'food' },
  { id: 48, name: 'たこ焼き', category: 'food' },
  { id: 49, name: '抹茶アイス', category: 'food' },
  { id: 50, name: 'りんご', category: 'food' },
  { id: 51, name: 'みかん', category: 'food' },
  { id: 52, name: 'いちご', category: 'food' },
  { id: 53, name: 'ぶどう', category: 'food' },
  { id: 54, name: 'スイカ', category: 'food' },
  { id: 55, name: 'メロン', category: 'food' },
  
  // 炎・光 (10個)
  { id: 56, name: '赤い炎', category: 'fire' },
  { id: 57, name: '青い炎', category: 'fire' },
  { id: 58, name: '緑の炎', category: 'fire' },
  { id: 59, name: '金の炎', category: 'fire' },
  { id: 60, name: '虹色の炎', category: 'fire' },
  { id: 61, name: '松明', category: 'fire' },
  { id: 62, name: 'ランタン', category: 'fire' },
  { id: 63, name: '炎の結晶', category: 'fire' },
  { id: 64, name: '太陽の欠片', category: 'fire' },
  { id: 65, name: '星の光', category: 'fire' },
  
  // 宝石 (15個)
  { id: 66, name: 'ルビー', category: 'gem' },
  { id: 67, name: 'サファイア', category: 'gem' },
  { id: 68, name: 'エメラルド', category: 'gem' },
  { id: 69, name: 'ダイヤモンド', category: 'gem' },
  { id: 70, name: 'アメジスト', category: 'gem' },
  { id: 71, name: 'トパーズ', category: 'gem' },
  { id: 72, name: 'オパール', category: 'gem' },
  { id: 73, name: '真珠', category: 'gem' },
  { id: 74, name: '琥珀', category: 'gem' },
  { id: 75, name: '翡翠', category: 'gem' },
  { id: 76, name: '水晶', category: 'gem' },
  { id: 77, name: '月長石', category: 'gem' },
  { id: 78, name: '星石', category: 'gem' },
  { id: 79, name: '虹石', category: 'gem' },
  { id: 80, name: '竜の涙', category: 'gem' },
  
  // 冒険アイテム (25個)
  { id: 81, name: '木の剣', category: 'adventure' },
  { id: 82, name: '鉄の剣', category: 'adventure' },
  { id: 83, name: '銀の剣', category: 'adventure' },
  { id: 84, name: '黄金の剣', category: 'adventure' },
  { id: 85, name: '伝説の剣', category: 'adventure' },
  { id: 86, name: '木の盾', category: 'adventure' },
  { id: 87, name: '鉄の盾', category: 'adventure' },
  { id: 88, name: '銀の盾', category: 'adventure' },
  { id: 89, name: '魔法の杖', category: 'adventure' },
  { id: 90, name: '賢者の杖', category: 'adventure' },
  { id: 91, name: '弓矢', category: 'adventure' },
  { id: 92, name: 'クロスボウ', category: 'adventure' },
  { id: 93, name: '斧', category: 'adventure' },
  { id: 94, name: 'ハンマー', category: 'adventure' },
  { id: 95, name: '槍', category: 'adventure' },
  { id: 96, name: 'ブーメラン', category: 'adventure' },
  { id: 97, name: '鉤爪', category: 'adventure' },
  { id: 98, name: 'ロープ', category: 'adventure' },
  { id: 99, name: 'コンパス', category: 'adventure' },
  { id: 100, name: '地図', category: 'adventure' },
  { id: 101, name: '望遠鏡', category: 'adventure' },
  { id: 102, name: '虫眼鏡', category: 'adventure' },
  { id: 103, name: 'リュック', category: 'adventure' },
  { id: 104, name: '水筒', category: 'adventure' },
  { id: 105, name: 'テント', category: 'adventure' },
  
  // ゲームアイテム (25個)
  { id: 106, name: 'HPポーション', category: 'game' },
  { id: 107, name: 'MPポーション', category: 'game' },
  { id: 108, name: '万能薬', category: 'game' },
  { id: 109, name: '解毒薬', category: 'game' },
  { id: 110, name: '蘇生薬', category: 'game' },
  { id: 111, name: '力の種', category: 'game' },
  { id: 112, name: '守りの種', category: 'game' },
  { id: 113, name: '速さの種', category: 'game' },
  { id: 114, name: '賢さの種', category: 'game' },
  { id: 115, name: '幸運の種', category: 'game' },
  { id: 116, name: '金貨', category: 'game' },
  { id: 117, name: '銀貨', category: 'game' },
  { id: 118, name: '銅貨', category: 'game' },
  { id: 119, name: '宝箱', category: 'game' },
  { id: 120, name: '鍵', category: 'game' },
  { id: 121, name: 'マスターキー', category: 'game' },
  { id: 122, name: '魔法の書', category: 'game' },
  { id: 123, name: '古代の巻物', category: 'game' },
  { id: 124, name: '羽ペン', category: 'game' },
  { id: 125, name: 'インク瓶', category: 'game' },
  { id: 126, name: '砂時計', category: 'game' },
  { id: 127, name: '懐中時計', category: 'game' },
  { id: 128, name: '魔法の鏡', category: 'game' },
  { id: 129, name: '水晶玉', category: 'game' },
  { id: 130, name: 'タロットカード', category: 'game' },
  
  // 追加アイテム (20個)
  { id: 131, name: '雲', category: 'nature' },
  { id: 132, name: '雨雲', category: 'nature' },
  { id: 133, name: '雷雲', category: 'nature' },
  { id: 134, name: '虹', category: 'nature' },
  { id: 135, name: '月', category: 'nature' },
  { id: 136, name: '星', category: 'nature' },
  { id: 137, name: '彗星', category: 'nature' },
  { id: 138, name: '花', category: 'nature' },
  { id: 139, name: '桜', category: 'nature' },
  { id: 140, name: '蝶', category: 'nature' },
  { id: 141, name: '鳥', category: 'nature' },
  { id: 142, name: 'フクロウ', category: 'nature' },
  { id: 143, name: '猫', category: 'animal' },
  { id: 144, name: '犬', category: 'animal' },
  { id: 145, name: 'ウサギ', category: 'animal' },
  { id: 146, name: 'クマ', category: 'animal' },
  { id: 147, name: 'ペンギン', category: 'animal' },
  { id: 148, name: 'リス', category: 'animal' },
  { id: 149, name: 'カエル', category: 'animal' },
  { id: 150, name: 'ドラゴン', category: 'animal' },
];

